#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

akamai_example_server_one:
  strategy: Akamai
  urls:
    - http://acme.com/au/images/clusters/2013/banner/lbobo-may-m-z-strip.jpg
    - /www.acme.com.au\/au\/images\/clusters\/2013\/banner\/pete-evans-may-banner.jpg/

varnish_example_server_one:
  strategy: Varnish
  proxies:
    - abcd-rp01.int.acme.com:80
    - abcd-rp02.int.acme.com:80
  urls:
    - http://www.acme.com/fountaingate/news-and-events/food-and-lifestyle/recipes/
    - http://cdnsa1.atacme.com/fountaingate/news-and-events/food-and-lifestyle/recipes/
    - http://www.acme.com/au/images/clusters/2013/banner/lbobo-may-2914.jpg

varnish_example_server_two:
  strategy: Varnish
  proxies:
    - abcd-rp03.int.acme.com:80
    - abcd-rp04.int.acme.com:80
  urls:
    - http://www.acme.com/au/images/clusters/2013/banner/lbobo-may-2914.jpg

cloud_front_example_server_one:
  strategy: CloudFront
  access_key: '123'
  secret_key: 'SECRET'
  distribution_id: 'DIST_ID_1'
  timeout_seconds: 1200
  urls:
    - /au/images/

cloud_front_example_server_two:
  strategy: CloudFront
  access_key: '123'
  secret_key: 'SECRET'
  distribution_id: 'DIST_ID_2'
  timeout_seconds: 1200
  urls:
    - /au/styles/
