# akamai_example_server_one:
#   strategy: Akamai
#   urls:
#     - http://cdnsa1.atwestfield.com/au/images/clusters/2013/banner/lbobo-may-m-z-strip.jpg
#     - /www.westfield.com.au\/au\/images\/clusters\/2013\/banner\/pete-evans-may-banner.jpg/

# varnish_example_server_one:
#   strategy: Varnish
#   proxies:
#     - ausyd-rp01.dbg.westfield.com:80
#     - ausyd-rp02.dbg.westfield.com:80
#   urls:
#     - http://www.westfield.com.au/fountaingate/news-and-events/food-and-lifestyle/recipes/
#     - http://cdnsa1.atwestfield.com/fountaingate/news-and-events/food-and-lifestyle/recipes/
#     - http://www.westfield.com.au/au/images/clusters/2013/banner/lbobo-may-2914.jpg

# varnish_example_server_two:
#   strategy: Varnish
#   proxies:
#     - aubdc-rp01.dbg.westfield.com:80
#     - aubdc-rp02.dbg.westfield.com:80
#   urls:
#     - http://www.westfield.com.au/au/images/clusters/2013/banner/lbobo-may-2914.jpg

# cloud_front_example_server_one:
#   strategy: CloudFront
#   access_key: '123'
#   secret_key: 'SECRET'
#   distribution_id: 'DIST_ID_1'
#   timeout_seconds: 1200
#   urls:
#     - /au/images/

# cloud_front_example_server_two:
#   strategy: CloudFront
#   access_key: '123'
#   secret_key: 'SECRET'
#   distribution_id: 'DIST_ID_2'
#   timeout_seconds: 1200
#   urls:
#     - /au/styles/
